development:
  adapter: async

test:
  adapter: async

production:
  adapter: postgres
  url: postgres://enzwupykhfkplh:b7bb366c27e2e44fe50aa032f10fe60919ab87dec84d96cdcce49db7be6ec95c@ec2-54-163-236-33.compute-1.amazonaws.com:5432/d6fsfcoaf3fbab